app_user: "roboshop"
component: "shipping"
url: "https://stan-robotshop.s3.amazonaws.com/shipping-v3.zip"
app_path: "/app"
setup_schema: true
schema: 
  - schema
  - app-user
  - master-data

secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/mysql token={{ token }} url=http://vault-tools.roboshop.internal:8200  validate_certs=False') }}"