- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3 install hvac

- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3.11 install hvac

- name: Configuring {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Injecting mysql schema for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: inject-mysql-schema
  when: setup_schema is defined

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname

