- name: Configuring {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname