- name: Disabling default nginx version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enabling  nginx 24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Installing nginx
  ansible.builtin.dnf:  
    name: nginx
    state: present  

- name: Copying the frontend roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/nginx.conf  

- name: Downloading {{ component }} content
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ app_path }}"
    remote_src: yes

- name: Starting nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes