app_user: "roboshop"
component: "payment"
url: "https://stan-robotshop.s3.amazonaws.com/payment-v3.zip"
app_path: "/app"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/rabbitmq token={{ token }} url=http://vault-tools.roboshop.internal:8200  validate_certs=False') }}"