- name: Installing {{ component }}
  ansible.builtin.dnf:  
    name: mysql-server
    state: present  

- name: Installing {{ component }}
  ansible.builtin.debug:  
    msg: This is {{ component }} role
    
- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3 install hvac

- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3.11 install hvac

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mysqld
    enabled: true

- name: Configuring root password for {{ component }}
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.mysql_pass }}

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname