- name: Configuring {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Configuring the repo for mongodb shell 
  ansible.builtin.template:
    src: mongodb.repo
    dest: "{{ repo_path }}"

- name: Installing mongodb shell
  ansible.builtin.dnf:  
    name: mongodb-mongosh
    state: present  

- name: Injecting schema 
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.roboshop.internal </app/db/master-data.js