- name: Installing mysql shell
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Injecting schema 
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{ env }}.roboshop.internal -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  when: setup_schema is defined