component: "mysql"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/mysql token={{ token }} url=http://vault-tools.roboshop.internal:8200  validate_certs=False') }}"