repo_path: "/etc/yum.repos.d/rabbitmq.repo"
component: "rabbitmq"
app_user: "roboshop"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/rabbitmq token={{ token }} url=http://vault-tools.roboshop.internal:8200  validate_certs=False') }}"